/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.conecel.claro.controllers;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import com.conecel.claro.dto.QuerySubscriberResponseMessage;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-22T12:39:21.861-05:00")

@Api(value = "Customer", description = "the Customer API")

public interface CustomerApi {

	@ApiOperation(value = "", 
			nickname = "querySubscriber", 
			notes = "Esta operaciÃ³n devuelve la informaciÃ³n bÃ¡sica del supscritor o Subscriber.", 
			response = QuerySubscriberResponseMessage.class, 
			tags = {})
	@ApiResponses(value = {
			@ApiResponse(code = 200, 
						message = "Devuelve la informaciÃ³n de la consulta de subscriptor.", 
						response = QuerySubscriberResponseMessage.class) })
	@GetMapping(value = "/Customer/Subscriber/v1/{subscriberType}/{subscriberId}", 
			produces = { "application/json" })
	ResponseEntity<QuerySubscriberResponseMessage> querySubscriber(
			@ApiParam(value = "Indica el tipo de identificaciÃ³n del subscriptor que se estÃ¡ suministrando para consultar la informaciÃ³n del mismo. EJEMPLO: SERVICENUMBER, IMSI, IMEI, ICCID", 
					required = true) 
			@PathVariable("subscriberType") String subscriberType,
			@ApiParam(value = "IdentificaciÃ³n unÃ­voca del subscriptor que se desea consultar a travÃ©s de Ã©sta operaciÃ³n.", 
					required = true) 
			@PathVariable("subscriberId") String subscriberId);

}
